### ISSUE TITLE
some different errors when "RUN cd sbmc && python setup.py develop" in cuda-sbmc.dockerfile

### ISSUE THREAD

**Issue by xywang-zju** [adobe/sbmc#15]
**error 1:**
Installed /sbmc_app/sbmc
Processing dependencies for sbmc==0.0.1
Searching for wget
Reading https://pypi.org/simple/wget/
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    main()
  File "setup.py", line 105, in main
    cmdclass=dict(build_ext=hlpt.HalideBuildExtension),
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/sbmc_app/anaconda/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/sbmc_app/anaconda/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/sbmc_app/anaconda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/setuptools/command/develop.py", line 156, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    not self.always_copy, self.local_index
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/setuptools/package_index.py", line 658, in fetch_distribution
    self.find_packages(requirement)
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/setuptools/package_index.py", line 491, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name + '/')
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/setuptools/package_index.py", line 831, in scan_url
    self.process_url(url, True)
  File "/sbmc_app/anaconda/lib/python3.7/site-packages/setuptools/package_index.py", line 361, in process_url
    page = f.read()
  File "/sbmc_app/anaconda/lib/python3.7/http/client.py", line 470, in read
    s = self._safe_read(self.length)
  File "/sbmc_app/anaconda/lib/python3.7/http/client.py", line 622, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(1992 bytes read, 1840 more expected)
The command '/bin/bash -c cd sbmc && python setup.py develop' returned a non-zero code: 1

**error 2:**
Installed /sbmc_app/sbmc
Processing dependencies for sbmc==0.0.1
Searching for wget
Reading https://pypi.org/simple/wget/
Downloading https://files.pythonhosted.org/packages/47/6a/62e288da7bcda82b935ff0c6cfe542970f04e29c756b0e147251b2fb251f/wget-3.2.zip#sha256=35e630eca2aa50ce998b9b1a127bb26b30dfee573702782aa982f875e3f16061
Best match: wget 3.2
Processing wget-3.2.zip
Writing /tmp/easy_install-la3hsewr/wget-3.2/setup.cfg
Running wget-3.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-la3hsewr/wget-3.2/egg-dist-tmp-dmrfue2p
zip_safe flag not set; analyzing archive contents...
Moving wget-3.2-py3.7.egg to /sbmc_app/anaconda/lib/python3.7/site-packages
Adding wget 3.2 to easy-install.pth file

Installed /sbmc_app/anaconda/lib/python3.7/site-packages/wget-3.2-py3.7.egg
Searching for lz4
Reading https://pypi.org/simple/lz4/
Downloading https://files.pythonhosted.org/packages/59/46/3ac0bb528c8e67ae2dad5692712be5e6ca5ccca8dda94a10801bcb741986/lz4-2.2.1-cp37-cp37m-manylinux1_x86_64.whl#sha256=95b8db1be938f5c17043bb9143bc120d270f7cebcb439686ec43d8c0b36b6377
Best match: lz4 2.2.1
Processing lz4-2.2.1-cp37-cp37m-manylinux1_x86_64.whl
Installing lz4-2.2.1-cp37-cp37m-manylinux1_x86_64.whl to /sbmc_app/anaconda/lib/python3.7/site-packages
writing requirements to /sbmc_app/anaconda/lib/python3.7/site-packages/lz4-2.2.1-py3.7-linux-x86_64.egg/EGG-INFO/requires.txt
Adding lz4 2.2.1 to easy-install.pth file

Installed /sbmc_app/anaconda/lib/python3.7/site-packages/lz4-2.2.1-py3.7-linux-x86_64.egg
Searching for scikit-image
Reading https://pypi.org/simple/scikit-image/
Downloading https://files.pythonhosted.org/packages/dc/48/454bf836d302465475e02bc0468b879302145b07a005174c409a5b5869c7/scikit_image-0.16.2-cp37-cp37m-manylinux1_x86_64.whl#sha256=2aa962aa82d815606d7dad7f045f5d7ca55c65b4320d47e15a98fc92612c2d6c
error: sha256 validation failed for scikit_image-0.16.2-cp37-cp37m-manylinux1_x86_64.whl; possible download problem?
The command '/bin/bash -c cd sbmc && python setup.py develop' returned a non-zero code: 1

**Comment by xywang-zju** [comment]
and **error 3**
Installed /sbmc_app/sbmc
Processing dependencies for sbmc==0.0.1
Searching for wget
Reading https://pypi.org/simple/wget/
Downloading https://files.pythonhosted.org/packages/47/6a/62e288da7bcda82b935ff0c6cfe542970f04e29c756b0e147251b2fb251f/wget-3.2.zip#sha256=35e630eca2aa50ce998b9b1a127bb26b30dfee573702782aa982f875e3f16061
error: Download error for https://files.pythonhosted.org/packages/47/6a/62e288da7bcda82b935ff0c6cfe542970f04e29c756b0e147251b2fb251f/wget-3.2.zip#sha256=35e630eca2aa50ce998b9b1a127bb26b30dfee573702782aa982f875e3f16061: [Errno 0] Error
The command '/bin/bash -c cd sbmc && python setup.py develop' returned a non-zero code: 1

**Comment by mgharbi** [comment]
it looks like pip cannot find the proper external dependencies on your machine. What's your environment? I've tested this on Ubuntu 16, 18 and OSX only.

**Comment by xywang-zju** [comment]
> it looks like pip cannot find the proper external dependencies on your machine. What's your environment? I've tested this on Ubuntu 16, 18 and OSX only.

thanks your reply,my environmrnt is windows,I'm now trying  to test on Ubuntu
